dima/DB/lab5_2/lab5_2/apps/admin_user1/urls.py
from django.urls import path

from . import views

app_name = 'admin_user1'
urlpatterns = [
    path('/components/', views.show_components, name='components'),
]

dima/DB/lab5_2/lab5_2/apps/authentication_form/urls.py
from django.urls import path

from . import views

app_name = 'main_form'
urlpatterns = [
    path('', views.index, name='index'),
    path('/check_user/', views.check_user, name='check_user')
]

dima/DB/lab5_2/lab5_2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('authentication_form.urls')),
    path('admin-user/', include('admin_user1.urls')),
    path('admin/', admin.site.urls),
]

dima/DB/lab5_2/lab5_2/apps/admin_user1/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.urls import reverse
from . import DB

def show_components(request):
    global a
    a = DB.DB('admin', 'admin')
    return render(request, 'admin_user1/show_components.html', {'components': a.show_components()})

dima/DB/lab5_2/lab5_2/apps/authentication_form/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.urls import reverse

def index(request):
    return render(request, 'authentication_form/main_form.html')

def check_user(request):
    a = (request.POST['login'], request.POST['password'],)
    print(a)
    return HttpResponse('ok')

dima/DB/lab5_2/lab5_2/templates/authentication_form/main_form.html
{% extends 'base.html' %}
{% block static %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'authentication_form/style.css' %}">
{% endblock %}
{% block title %}Аутентификация{% endblock %}

{% block content %}

    <form action="{% url 'main_form:check_user'%}" method="POST">

        {% csrf_token %}

        <div class="main_form">
            <div class="input-group">
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text change_size_form fix_padding_main_form" id="inputGroup-sizing-default">Логин</span>
                    </div>
                    <input type="text" name="login" class="form-control" aria-label="Default"
                           aria-describedby="inputGroup-sizing-default">
                </div>
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text change_size_form" id="inputGroup-sizing-default">Пароль</span>
                    </div>
                    <input type="text" name="password" class="form-control" aria-label="Default"
                           aria-describedby="inputGroup-sizing-default">
                </div>
            </div>
            <button type="sumbit" class="btn btn-success button_center">Войти</button>
        </div>



    </form>
{% endblock %}

dima/DB/lab5_2/lab5_2/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Мой сайт{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block static %}{% endblock %}
</head>
<body>

    {% block content %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>